/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    industries: Industry;
    cases: Case;
    portfolio: Portfolio;
    posts: Post;
    team: Team;
    testimonials: Testimonial;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    cases: CasesSelect<false> | CasesSelect<true>;
    portfolio: PortfolioSelect<false> | PortfolioSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    editorial: Editorial;
    navigation: Navigation;
    avisoPrivacidad: AvisoPrivacidad;
    politicaCookies: PoliticaCooky;
    contratoServicios: ContratoServicio;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    editorial: EditorialSelect<false> | EditorialSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    avisoPrivacidad: AvisoPrivacidadSelect<false> | AvisoPrivacidadSelect<true>;
    politicaCookies: PoliticaCookiesSelect<false> | PoliticaCookiesSelect<true>;
    contratoServicios: ContratoServiciosSelect<false> | ContratoServiciosSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Cuentas con acceso al panel administrativo. Solo administradores pueden crear/editar usuarios.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role?: ('admin' | 'editor' | 'redactor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Imágenes, videos y documentos subidos. Se referencian desde otros campos (cover, gallery, etc.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    avatar?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Las disciplinas que la agencia ofrece. Aparecen en home (sección Servicios) y en /servicios.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * Ejemplo: marketing-360 (en minúsculas, sin espacios)
   */
  slug: string;
  icon?: ('Brain' | 'Layout' | 'Megaphone' | 'Palette' | 'PlayCircle' | 'TrendingUp' | 'Sparkles') | null;
  shortDescription: string;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Verticales que dominamos. Aparecen en home (sección Industrias) y como filtros en /industrias.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  name: string;
  slug: string;
  icon?: ('Scale' | 'Stethoscope' | 'Users' | 'ShoppingBag' | 'Landmark') | null;
  shortDescription: string;
  comingSoon?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Casos de éxito con métricas tangibles (ROI, leads, revenue). Mostrar resultados que se midieron. Distinto de Portafolio (que es showcase visual).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases".
 */
export interface Case {
  id: number;
  title: string;
  slug: string;
  client?: string | null;
  industry?: (number | null) | Industry;
  services?: (number | Service)[] | null;
  year: number;
  /**
   * El número grande, ej. '+312%' o 'Top 3' o '+1,800'
   */
  metric?: string | null;
  /**
   * Qué mide el número. Ej: 'leads calificados', 'ranking en Google búsqueda local', 'miembros activos'.
   */
  metricLabel?: string | null;
  /**
   * Ventana de tiempo en la que se logró el resultado. Ej: '12 meses', '8 meses', '12 meses post-lanzamiento'.
   */
  metricPeriod?: string | null;
  /**
   * Contra qué se compara la métrica. Ej: 'vs. baseline 2024', 'antes en posiciones 12-18', 'duplicó la base anterior'.
   */
  metricBaseline?: string | null;
  /**
   * Aporta credibilidad E-E-A-T a Google y AI engines: cómo se midió, fuente del dato, qué tooling se usó. Ejemplo: 'Conteo de leads cualificados por el equipo comercial. Fuente: CRM interno auditado mensualmente. Solo prospectos con propuesta enviada.'
   */
  metricSource?: string | null;
  cover?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featured?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Showcase visual: branding, identidad, sistemas de marca, video. Pieza visual sin obligación de métricas. Distinto de Casos (que sí lleva ROI/resultados).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio".
 */
export interface Portfolio {
  id: number;
  title: string;
  slug: string;
  client?: string | null;
  category: 'branding' | 'design-system' | 'logo' | 'packaging' | 'editorial' | 'web' | 'campaign' | 'other';
  year: number;
  industry?: (number | null) | Industry;
  /**
   * Imagen estática de fallback. Si pones un videoUrl, este se usa como póster mientras carga el video. Aspect ratio sugerido 4:5 o 3:4.
   */
  cover?: (number | null) | Media;
  /**
   * URL pública del video. Soporta vimeo.com/{id}, player.vimeo.com/video/{id}, youtube.com/watch?v={id}, youtu.be/{id}. Si está, reemplaza la imagen estática en la card como autoplay muted loop.
   */
  videoUrl?: string | null;
  gallery?: (number | Media)[] | null;
  /**
   * 1-2 frases que aparecen en la card al hover.
   */
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  tools?:
    | {
        tool?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Link a Behance, Dribbble, sitio del cliente, etc. Si está vacío, el card abre la página interna del proyecto.
   */
  externalUrl?: string | null;
  featured?: boolean | null;
  order?: number | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Diario satma. Artículos, ensayos y aprendizajes del equipo. Soportan drafts y se publican manual.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  cover?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (number | null) | User;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Personas detrás de SATMA. Aparecen en /agencia → sección "Personas detrás de SATMA". Si dejas la foto en blanco se muestra una inicial estilizada como fallback. La entrada "Santiago Álvarez" se filtra automáticamente porque tiene su sección dedicada arriba.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  /**
   * Foto pensada para modo noche (fondo oscuro). Si solo subís UNA foto se usa en ambos modos. Resolución mínima 800×800 px, formatos JPG/PNG/WebP.
   */
  photo?: (number | null) | Media;
  /**
   * Variante para modo día (fondo claro). Opcional — si la dejás en blanco, modo día usa la foto principal de arriba.
   */
  photoLight?: (number | null) | Media;
  /**
   * Ciudad donde vive / opera la persona. Aparece como subtítulo en la card.
   */
  location?: string | null;
  bio?: string | null;
  linkedin?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Citas de clientes. Aparecen en home (sección Lo que dicen) y en /agencia.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  author: string;
  role?: string | null;
  company?: string | null;
  photo?: (number | null) | Media;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'cases';
        value: number | Case;
      } | null)
    | ({
        relationTo: 'portfolio';
        value: number | Portfolio;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        avatar?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  shortDescription?: T;
  longDescription?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  shortDescription?: T;
  comingSoon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases_select".
 */
export interface CasesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  industry?: T;
  services?: T;
  year?: T;
  metric?: T;
  metricLabel?: T;
  metricPeriod?: T;
  metricBaseline?: T;
  metricSource?: T;
  cover?: T;
  gallery?: T;
  summary?: T;
  body?: T;
  featured?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio_select".
 */
export interface PortfolioSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  category?: T;
  year?: T;
  industry?: T;
  cover?: T;
  videoUrl?: T;
  gallery?: T;
  summary?: T;
  body?: T;
  tools?:
    | T
    | {
        tool?: T;
        id?: T;
      };
  externalUrl?: T;
  featured?: T;
  order?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  author?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  photoLight?: T;
  location?: T;
  bio?: T;
  linkedin?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  role?: T;
  company?: T;
  photo?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Datos globales: nombre del sitio, contacto, redes sociales. Lo que cambia aquí se actualiza en header, footer y formularios.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  description?: string | null;
  logo?: (number | null) | Media;
  email?: string | null;
  phone?: string | null;
  phoneAlt?: string | null;
  addressStreet?: string | null;
  addressNeighborhood?: string | null;
  addressCity?: string | null;
  addressState?: string | null;
  addressZip?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  x?: string | null;
  linkedin?: string | null;
  heroBadge?: string | null;
  heroHeadline?: string | null;
  heroSubheadline?: string | null;
  heroCtaPrimaryLabel?: string | null;
  heroCtaPrimaryHref?: string | null;
  heroCtaSecondaryLabel?: string | null;
  heroCtaSecondaryHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Copy editorial de las secciones del home y /agencia: manifiesto, proceso, slogan del CTA final, stats y valores. Cambiar aquí actualiza el sitio público al instante.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editorial".
 */
export interface Editorial {
  id: number;
  manifestoEyebrow?: string | null;
  manifestoHeadline?: string | null;
  manifestoBody?: string | null;
  manifestoPilares?:
    | {
        number?: string | null;
        title?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  processEyebrow?: string | null;
  processHeadline?: string | null;
  processFases?:
    | {
        number?: string | null;
        title?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Línea italic encima del headline. La separación con punto en "Agenc.IA" hace el wordplay agencia + IA.
   */
  ctaEyebrow?: string | null;
  ctaHeadline?: string | null;
  ctaSubheadlineBefore?: string | null;
  ctaSubheadlineEmphasis?: string | null;
  ctaPrompt?: string | null;
  ctaPrimaryLabel?: string | null;
  ctaSecondaryLabel?: string | null;
  agenciaStats?:
    | {
        value?: number | null;
        prefix?: string | null;
        suffix?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  valoresEyebrow?: string | null;
  valoresHeadline?: string | null;
  valoresIntro?: string | null;
  valores?:
    | {
        title?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  santiagoEyebrow?: string | null;
  santiagoRolePill?: string | null;
  santiagoBioParagraphs?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  santiagoCredentials?:
    | {
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controla qué secciones aparecen en el menú del sitio (header, footer, móvil). Marcar 'Visible' muestra el ítem; desmarcarlo lo oculta sin borrarlo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Cada fila es un link del menú. Reordená arrastrando. Desmarcá 'Visible' para ocultar sin borrar.
   */
  items?:
    | {
        label: string;
        /**
         * Ruta interna (con slash inicial, ej. '/servicios') o URL completa (ej. 'https://...').
         */
        href: string;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Documento público en /aviso-privacidad. Cumplimiento LFPDPPP (México). Cambiar aquí actualiza la página al instante.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avisoPrivacidad".
 */
export interface AvisoPrivacidad {
  id: number;
  title: string;
  /**
   * Texto que aparece como subtítulo. Ej: '27 de abril de 2026'.
   */
  lastUpdated: string;
  /**
   * Editor enriquecido. Soporta encabezados (H2/H3), párrafos, listas, negritas, italics, links. Si lo dejás vacío, la página se renderiza sin contenido — recomendado usar siempre.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Documento público en /politica-cookies. Tipos de cookies usadas y cómo desactivarlas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "politicaCookies".
 */
export interface PoliticaCooky {
  id: number;
  title: string;
  /**
   * Texto que aparece como subtítulo. Ej: '27 de abril de 2026'.
   */
  lastUpdated: string;
  /**
   * Editor enriquecido. Soporta encabezados (H2/H3), párrafos, listas, negritas, italics, links. Si lo dejás vacío, la página se renderiza sin contenido — recomendado usar siempre.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Documento público en /contrato-servicios. Términos generales de prestación de servicios SATMA → cliente.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contratoServicios".
 */
export interface ContratoServicio {
  id: number;
  title: string;
  /**
   * Texto que aparece como subtítulo. Ej: '27 de abril de 2026'.
   */
  lastUpdated: string;
  /**
   * Editor enriquecido. Soporta encabezados (H2/H3), párrafos, listas, negritas, italics, links. Si lo dejás vacío, la página se renderiza sin contenido — recomendado usar siempre.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  logo?: T;
  email?: T;
  phone?: T;
  phoneAlt?: T;
  addressStreet?: T;
  addressNeighborhood?: T;
  addressCity?: T;
  addressState?: T;
  addressZip?: T;
  instagram?: T;
  facebook?: T;
  x?: T;
  linkedin?: T;
  heroBadge?: T;
  heroHeadline?: T;
  heroSubheadline?: T;
  heroCtaPrimaryLabel?: T;
  heroCtaPrimaryHref?: T;
  heroCtaSecondaryLabel?: T;
  heroCtaSecondaryHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editorial_select".
 */
export interface EditorialSelect<T extends boolean = true> {
  manifestoEyebrow?: T;
  manifestoHeadline?: T;
  manifestoBody?: T;
  manifestoPilares?:
    | T
    | {
        number?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  processEyebrow?: T;
  processHeadline?: T;
  processFases?:
    | T
    | {
        number?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  ctaEyebrow?: T;
  ctaHeadline?: T;
  ctaSubheadlineBefore?: T;
  ctaSubheadlineEmphasis?: T;
  ctaPrompt?: T;
  ctaPrimaryLabel?: T;
  ctaSecondaryLabel?: T;
  agenciaStats?:
    | T
    | {
        value?: T;
        prefix?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  valoresEyebrow?: T;
  valoresHeadline?: T;
  valoresIntro?: T;
  valores?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  santiagoEyebrow?: T;
  santiagoRolePill?: T;
  santiagoBioParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  santiagoCredentials?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        enabled?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avisoPrivacidad_select".
 */
export interface AvisoPrivacidadSelect<T extends boolean = true> {
  title?: T;
  lastUpdated?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "politicaCookies_select".
 */
export interface PoliticaCookiesSelect<T extends boolean = true> {
  title?: T;
  lastUpdated?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contratoServicios_select".
 */
export interface ContratoServiciosSelect<T extends boolean = true> {
  title?: T;
  lastUpdated?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}